### ISSUE TITLE
App.js: [BABEL]: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by shivamvijaywargi** [marklawlor/nativewind#106]
I have tried installing the nativewind both with npm and yarn and both the packages the new and the old one but still for some reason it keeps on throwing the error App.js: [BABEL]: Cannot find module 'node:path'

![image](https://user-images.githubusercontent.com/29519495/177827558-d7465cc3-62d6-4889-b9fc-a81b6a985d90.png)

I tried searching online for some solution but had no luck.

I would highly appreciate it if someone could help me with what I am doing wrong.

Thanks in advance.

**Comment by marklawlor** [comment]
Hi @shivamvijaywargi, what version of NodeJS are you using?

**Comment by sathishobili** [comment]
> Hi @shivamvijaywargi, what version of NodeJS are you using?

I am also have same issues,  Node -v (v14.17.2) , when add plugins: ['tailwindcss-react-native/babel'] in babel.config.js , then error is coming

**Comment by marklawlor** [comment]
The issue is the `node:` prefixes were added in `14.18`. I'm inclined not to fix this and simply change the supported version to `14.20` (last version of 14, which people should be on for the security patches) or even Node `16` (current LTS).

I'm going to think about this more over the weekend, but the immediate fix is simply update your version of node.

**Comment by shivamvijaywargi** [comment]
@marklawlor Even I was using v14.17.0. I have upgraded to node v16 and now it is working fine. Thank you :)
