### ISSUE TITLE
Getting "Cannot read property 'displayName' of undefined" while testing components.

### ISSUE THREAD

**Issue by Saad-Bashar** [marklawlor/nativewind#220]
**Describe the bug**
Getting this error `Cannot read property 'displayName' of undefined` while trying to run test on my component with react-native-testing-library. Please check the image below. 

![Screenshot 2022-08-31 at 2 32 38 PM](https://user-images.githubusercontent.com/13269141/187633806-6f5f8b64-586e-4ceb-809a-e036f8cf9d9d.png)
![Screenshot 2022-08-31 at 2 56 36 PM](https://user-images.githubusercontent.com/13269141/187639933-4bea596a-be18-4d9e-8730-7ac73e77cbd4.png)

Not sure if this is related to this somehow, https://stackoverflow.com/a/69587148. Thanks!

**Comment by Saad-Bashar** [comment]
I just updated to the latest nativewind and I am getting a new error while trying to run the tests. It says `TypeError: _nativewind.NativeWindStyleSheet.parse is not a function`

Interestingly I also got the same error on simulator but after resetting the cache by `react-native-start --reset-cache`, I do not get that error running the app. However, still getting the error running the tests. I have tried to clean yarn cache as well.

**Comment by marklawlor** [comment]
`NativeWindStyleSheet.parse` was removed before `2.0.0`. It appears you are still loading a cached file.

`Cannot read property 'displayName' of undefined` I can replicate this error, but only when I pass an undefined value into `styled()` or use className on an invalid element eg `<View2 className="" />`. I'm going to improve the error message, but that won't resolve your issue.

Are you able to share your repo with this issue? Sharing the error message without the cause is basically asking me to fix an issue blindly.

**Comment by Saad-Bashar** [comment]
Thank you for your quick response as always, as this is company's repo, I can not share the repo. But I am trying to create a repo with this issue.

**Comment by Saad-Bashar** [comment]
So after restarting my Mac, this error is not coming up anymore `NativeWindStyleSheet.parse` but still getting the `displayName of undefined` error. Trying to create a brand new project and reproducing the issue. Thanks!

**Comment by Saad-Bashar** [comment]
Alright, while reproducing the issue I fixed the problem! Was such a silly mistake. I was importing `<TouchableOpacity />` from gesture module instead of `react-native`. Hence I was getting the `displayName of undefined error`. At the end it was the auto-import extension that caused me a day 😭 Sorry for giving you the unnecessary trouble. 🙏🏻
