### ISSUE TITLE
Expo example not working in native with imported css

### ISSUE THREAD

**Issue by carlosmagoo** [marklawlor/nativewind#249]
**Describe the bug**
The expo example given in ./examples/expo, only works with inline tailwind css. Whenever you declare a class inside the ./styles/main.css, and use it in the components it won't apply the css. This works on "web" not when used on a mobile device.

Any reasons for this? 

**To Reproduce**
Setup https://github.com/marklawlor/nativewind/tree/main/examples/expo project, use "yarn" to install, and add css to main.css and see if it applies to the components. Test on any mobile device.

**Expected behavior**
Expected is that the css declared inside main.css would apply to the components  when using the class inside "className" prop.

**Comment by marklawlor** [comment]
This is expected behaviour.

On native, the `main.css` file isn't loaded - its only loaded while on the web platform.

Additionally, writing custom css is currently out of scope for this project. This library is simply trying to get Tailwind CSS class' working in React Native, not be a complete CSS engine.

If you do want custom styles, you can add them via Tailwinds plugin system

**Comment by carlosmagoo** [comment]
How would u set it up using tailwinds plugin system?

**Comment by marklawlor** [comment]
It is well documented on the Tailwind site https://tailwindcss.com/docs/plugins

There are also numerous tutorials available online.
