### ISSUE TITLE
Typed className

### ISSUE THREAD

**Issue by steida** [marklawlor/nativewind#325]
I believe it should be possible to have a fully typed className based on everything what Tailwind provides. Maybe it's a task for Tailwind itself, I am leaving it here only as a suggestion. WDYT?

**Comment by marklawlor** [comment]
I'm going to close this as I consider it out of scope for this project, but I'll share my thoughts why.

Proper types cannot be statically generated, so you either need to perform code generation or provide a Typescript Language Plugin. This is because Tailwind itself is dynamic. Not only are there arbitrary classes but plugins that can dynamicly add and remove classes. There are already packages out there that try and solve this problem but they seem largely unmaintained.

The web community are the biggest users of Typescript and Tailwind. Both are at their biggest hype levels and nobody seems to be requesting fully typed Tailwind. I believe this is because (with the intellisense plugin) the experience using Tailwind is good enough that developers don't feel like they need it. Types provide guarantees that code will always run as expected but CSS/Tailwind isn't traditional code and doesn't have the problems that types typically fix (it has its own set of problems :laughing:)

**Comment by steida** [comment]
I understand and thank you for the answer. I was curious because I suppose "proper types can be statically generated" with template literal types. There is no reason why it should not, except for the ecosystem itself. I agree it's out of the scope of Nativewind. I will ask in Tailwind repo 😇
