### ISSUE TITLE
NativeWind production build is different from dev on Web

### ISSUE THREAD

**Issue by voody2506** [marklawlor/nativewind#453]
Hi. My NativeWind production build is different from the dev build in flex-row style. I Tested on local and Vercel

<img width="236" alt="Снимок экрана 2023-03-30 в 05 33 28" src="https://user-images.githubusercontent.com/16849759/229232322-476268a9-5615-4a41-9353-5b676f5a680d.png">
<img width="227" alt="Снимок экрана 2023-03-30 в 05 34 03" src="https://user-images.githubusercontent.com/16849759/229232329-fd36a40d-e212-4f38-94e7-c2786d553491.png">

**Comment by voody2506** [comment]
I am using Solito Monorepo and my tailwind.config.js is 

`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    '../../packages/**/*.{js,jsx,ts,tsx}',
  ],
  plugins: [require('nativewind/tailwind/css')],
  important: 'html',
  theme: {
    ...theme,
  },
`

**Comment by Jemaz** [comment]
Getting same issue here and honestly it's driving me up the walls for days.

It happens when using nativewind and Next.js together. Running `yarn next` the dev server shows the output correctly.
 
However, running the build server for production (`yarn build` & `yarn start`) shows missing styles applied (exactly like the screenshots above) and the actual css output by comparing next.js's css output and the output from `npx tailwind -o output.css` are shown below side by side, as you can see, the css selectors are wrong: 
![CleanShot 2023-04-03 at 05 43 43](https://user-images.githubusercontent.com/7013450/229400105-b7b76046-ca4c-4722-b696-970ba8f6e114.png)

If anyone can correct me or guide me to solving this, I'd be extremely happy.

**Comment by voody2506** [comment]
@Jemaz Hi, I found solution 
https://github.com/nandorojo/solito/pull/369

1) Update Next JS
2) Yarn on monorepo

This fixed everything
