### ISSUE TITLE
App Crashes unexpectedly.

### ISSUE THREAD

**Issue by asiflhr** [marklawlor/nativewind#480]
**Describe the bug**
Hy I'm using nativewind with react-native-cli, wix/react-native-navigation. and app crashing unexpectedly and getting the error.

**Expected behavior**
I'm using nativewind with react-native-cli, wix/react-native-navigation. and app crashing unexpectedly and getting the error.
```javascript
error: index.js: [BABEL] C:\Users\CYRUS\Documents\work\ux-labs\MyApp\index.js: Unexpected token ',' (While processing: "C:\\Users\\CYRUS\\Documents\\work\\ux-labs\\MyApp\\node_modules\\nativewind\\babel.js")
``` 

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/26629776/1a569a82-3de4-4bed-bbf6-073602221f5f)
![image](https://github.com/marklawlor/nativewind/assets/26629776/318567b9-b52a-495a-a901-a50a8376ce17)
![image](https://github.com/marklawlor/nativewind/assets/26629776/1596334b-96ea-45e4-9a61-955146d9b64b)

**Comment by marklawlor** [comment]
You are getting this error because babel is having problems transforming one of your files. But without access to your code, I cannot tell which file or why it causes an error.

I"m going to close this issue as I cannot assist further but if your still having problems please create a new issue with a link to your repo so I can debug the problem
