### ISSUE TITLE
V4 not working in react-native-cli

### ISSUE THREAD

**Issue by andrefelipeschulle** [marklawlor/nativewind#535]
**Describe the bug**
nativewind 4.0.0-alpha.4, is not working, it is configured according to doc v4, but still no effect on the app.
no visual effect.

**Configs**

```javascript
babel.config.js

module.exports = {
  presets: ['module:metro-react-native-babel-preset', 'nativewind/babel'],
  plugins: ['react-native-reanimated/plugin'],
};
```

```javascript
metro.config.js

const {getDefaultConfig} = require('@react-native/metro-config');
const {withNativeWind} = require('nativewind/metro');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
let config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, {input: './global.css'});

```

```javascript
tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
  presets: [require('nativewind/preset').default],
};

```

global.css in root
```css
global.css

@tailwind base;
@tailwind components;
@tailwind utilities;
```

```jsx
App.tsx

import React from 'react';
import {Text, View} from 'react-native';

import {verifyInstallation} from 'nativewind';

import '../global.css';

export function App() {
  verifyInstallation();
  return (
    <View className="flex-1 bg-white">
      <Text className="text-red-500">teste</Text>
    </View>
  );
}
```

terminal build info
![Captura de Tela 2023-08-18 às 11 51 24](https://github.com/marklawlor/nativewind/assets/33896558/eb474086-5ac2-4c9a-bed2-4c61044fa5ac)

**Comment by atanaskanchev** [comment]
Same in my expo-router project, the styles are not applied so I've downgraded to v3

**Comment by marklawlor** [comment]
I appreciate the enthusiasm but I'm going to have to close this issue simply due to lack of information.

I've had a lot of people ask to be testers, so I'm going to write this as a general message for the community. Please don't take this personally, your issue just happens to be a good practical example for this message.

If I was a tester and the setup was not working, then I would come to two conclusions: either the instructions are incorrect or there is another unknown problem. 
 
I can verify the instructions are correct by creating a new repo `npx react-native@latest init` and re-doing the setup. Doing so, I can verify that NativeWind is working so we now know there is an unknown problem. At this stage, simply creating a issue with a link to your repo would be an acceptable bug report. But if you want to be a tester, then I would expect some issue isolation, or at least a list of troubleshooting steps you have tried.
 
I would really love for another contributor to join NativeWind and help with the testing. But being a tester isn't about finding bugs - its about reporting them. So if people are serious about contributing as a tester, I just need them to demonstrate that they can provide quality issue reports. If you do so, I'll take notice, and I'll be the one chasing you.
