### ISSUE TITLE
Question: how to handle dynamic theme colors

### ISSUE THREAD

**Issue by mustafaskyer** [marklawlor/nativewind#588]
Hello,
thanks for your great work here, appreciated 🙏
my question is how to handle dynamic theme colors, and fonts.
For example I've colors that will fetch from server, and want to set theme based on server response!

thanks in advance

**Comment by surgeharb** [comment]
Hi, I usually add theme variable as a style with colors to be set as CSS variables. Here is a simple example from this repo: https://github.com/marklawlor/nativewind/blob/main/examples/expo-router/app/(tabs)/index.tsx#L10

More advanced setup that I am using:
- Wrap your components with this [Wrapper](https://github.com/nodegram/nativeflare/blob/main/packages/ui/components/_wrapper.tsx#L16)
- Colors can be a Ts/Js variable that can come from your files or the server ([example](https://github.com/nodegram/nativeflare/blob/main/packages/ui/config/colors.tsx))
- Tailwind CSS file will look more like this then: https://github.com/nodegram/nativeflare/blob/main/apps/expo-demo/tailwind.config.js

NativeFlare is also an open-source project on top of NativeWind which will provide the community more guidelines on building an easy and structured design system for React Native. I will be pushing some updated to the docs this week in order to share knowledge on how to setup on your own!

**Comment by marklawlor** [comment]
Current NativeWind (v2) cannot handle this. Like mention above, v4 will allow you to use CSS variables for dynamic values.
