### ISSUE TITLE
border-r doesn't work with nativewind 4

### ISSUE THREAD

**Issue by pencilcheck** [marklawlor/nativewind#721]
**Describe the bug**

border-r doesn't work with nativewind 4

**To Reproduce**
1. Create a view
```
          <View className="p-4 border-r flex-1 items-center">
          </View>
```
Doesn't work.

But this
```
          <View style={{ borderRightWidth: 1 }} className="p-4 flex-1 items-center">
          </View>
```
works.

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
I'm unable to reproduce the issue. If the issue still occurs after resetting your cache, please respond with a full reproduction - there is most likely something else causing the issue

**Comment by marklawlor** [comment]
The view has the border for me and the unit tests also pass and report there is a border.

Like I originally said, I need more information/context to help you. e.g `react-native-windows` does not support setting borders on one side, so this class will fail because it's not supported by the platform. But without any extra information, I can't provide any additional assistance.
