### ISSUE TITLE
V4 - Styles not applying on Expo when run the server with --tunnel flag

### ISSUE THREAD

**Issue by donnes** [marklawlor/nativewind#737]
**Describe the bug**
When I try to run the app starting the Expo server using the flag `--tunnel`. Like `expo start --tunnel` the styles are not being applied.

**To Reproduce**

- Clone repo https://github.com/fendyk/expo-router-typescript-nativewind-example
- Start Expo server with `--tunnel` flag enabled. e.g `expo start --tunnel`
- Open the app on Android or iOS
- Observe that certain classes do not apply any styling

**Expected behavior:**
All Tailwind CSS classes should be correctly parsed and applied, resulting in the intended styles being reflected on the elements.

Related to https://github.com/marklawlor/nativewind/issues/648

**Comment by marklawlor** [comment]
This might be a tricky one to implement. `--tunnel` setups a tunnel on a specific port that Metro uses to provide the new JavaScript for fast-reload. In development, NativeWind sets up its own websocket connection (on a different port) to provide the styles. Different ports and different protocols, that's why the styles are not coming thought.

For it to work, we would need to send on the same connection as Metro, and intercept it before Metro does. I don't think this is exposed anywhere, so it might involve extending the entire Expo development server. Its going to be a big task :thinking: 

Or, maybe it could revert back to v2 behaviour. In v2 we used Babel to inject the styles, but it was not reliable and you would often need to reset your babel cache.

**Comment by donnes** [comment]
@marklawlor Thanks for your reply. Actually it seems to be a challenge.
I will try to play around the WebSocket or Metro and see if I can get it working.

**Comment by mtreilly** [comment]
If there is anything you find worth investigating, please do share, can help with anything. Don't currently have to face the same issue, but with planned app changeover realise this may become something I need to add later

**Comment by WillSmithTE** [comment]
wow this is a great find, i was going crazy trying to work out what was wrong here.

would it be worth adding a note to the [expo quick start](https://www.nativewind.dev/quick-starts/expo) about running with `--tunnel`?

**Comment by marklawlor** [comment]
`4.0.28` now uses http and should work with `--tunnel`
