### ISSUE TITLE
Cannot convert null value to object

### ISSUE THREAD

**Issue by GustavoBonfimS** [marklawlor/nativewind#745]
**Describe the bug**
After upgrading Expo to SDK 50 preview > 8, Nativewind breaks in native builds when i use a icon from @expo/vector-icons

**To Reproduce**
1. Create a project with Expo SDK 50 preview
2. Install nativewind
3. Use some icon from @expo/vector-icons

**Expected behavior**
Icons render correctly

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/50304935/343f49bc-9465-4cf5-9959-416e4152bd46)

**Additional context**

**Comment by hirbod** [comment]
I can confirm this issue. I reported this to Expo but just figured that it happens inside react-native-css-interop and only breaks with vector-icons v14 and Expo SDK 50

**Comment by GustavoBonfimS** [comment]
Mark seems a little busy and I don't know how to help just yet.

To continue with the builds in my project I needed to change all the icons to lucid-react-native... It wasn't an easy job but it was already in my plans.

**Comment by intergalacticspacehighway** [comment]
The root cause here is related to two issues.

1. vector-icons v14/expo-module-scripts upgrade leading to slightly different build output.
2. `react-native-css-interop` assuming props cannot be null.

This [line](https://github.com/expo/vector-icons/blob/ae4c732387ce4a1d9a1b0c9df1cae3178c061f9b/build/createIconSet.js#L44) in vector-icon v14 is causing issue and making it incompatible with nativewind. Before [expo-module-scripts upgrade](https://github.com/expo/vector-icons/pull/279/files) the build output was different and JSX syntax was preserved, props i think by default is an empty object instead of `null`, so nativewind assumes it to be an empty object.


The issue with nativewind is min reproducible by rendering below component `<MyComp />`. The issue happens when props are `null`.

```
const MyComp = () => {
  return React.createElement(View, null)
}
```

Simple fix can be adding a null check `react-native-css-interop` below. I couldn't find below code in main branch of `react-native-css-interop`. So maybe this is already fixed and not released? 🤔 

<img width="834" alt="Screenshot 2024-01-18 at 10 14 31 AM" src="https://github.com/marklawlor/nativewind/assets/23293248/607802eb-fb5f-4e2c-85b6-1e26bf9d2d80">

**Comment by hirbod** [comment]
Thanks to both of you. Great digging nishan! ❤️. 

Gonna prepare an interim patch for now.

**Comment by marklawlor** [comment]
Please try `4.0.23`
