### ISSUE TITLE
More Frequent releases while in Beta

### ISSUE THREAD

**Issue by panzacoder** [marklawlor/nativewind#748]
Hey there, small request.

I know dev is slow right now, but I notice that there have been steady releases over the last month, and `4.0.22` is looking a little stale. Since we are testing Beta, I think it would be nice if we could get access to the newest changes so we can jump between patch versions to see what is working well for small bug fixes.

For instance, I have some errors that are happening in the interop code, and it looks like you've rewritten that quite a bit since my release, so it would be good to install the latest and see if I need to open a bug report.

Thanks! Appreciate your work on this project. If your community can help you reach your next release let us know how!

**Comment by marklawlor** [comment]
The delay on the next version is due to community feedback :sweat_smile: As you've noticed, this is mostly around the interop and it has been quite a large rewrite - which also means I need to retest the library before I'm confident its stable again.

Unfortunately, I think its gone slightly in the wrong direction, with the current code on `main` causing to many cascading rerenders :cry: Once I address this, then I'll be back to the frequent release cycle and catching up the backlog of issues.

**Comment by panzacoder** [comment]
Yeah, that makes a lot of sense. I am very excited about the project so I am sure many others are also!

It sounds like the problem you are working through is a bit of a deep problem, please let us all know if there is a particular aspect of it that needs testing or research!
