### ISSUE TITLE
[V4] - cssInterop ignores leading-none and other leading classes

### ISSUE THREAD

**Issue by MikhailR1337** [marklawlor/nativewind#781]
**Describe the bug**
I updated from 2.0.11 to 4.0.13 (I've tried 4.0.23 but it doesn't work correctly with useAnimatedStyle in some cases)
I really tried to substitute styled() with cssInterop, but due to the issue with leading I really confused how to make it

styled() was a wrapper for some components that provides prop className as a result I've been trying to implement similar HOC function but with cssInterop.
Some cases work - like colors, font-size and so on, but some cases don't

**Expected behavior**
I expect that all that I put inside prop className would work correctly

**Additional context**
Perhaps you can include styled() in v.4 release?

**Comment by marklawlor** [comment]
I'm going to close this issue because I'm lost to what your asking. Your reporting multiple things with no context and also including a feature request to return `styled()`?

Please resubmit these as separate issues with good descriptions with one topic per issue. I'd like to help, but I'm a bit lost

- `leading-*` should work. If it doesn't please clarify in your issue
- `styled()` was removed as should be no longer needed. Please state why you need this
- "some cases don't"  what cases? I can't fix issues if they are not reported
