### ISSUE TITLE
v4: viewTag is not working in android

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [marklawlor/nativewind#791]
**Describe the bug**
Android:  appContext.findView<xxx>(viewTag) can not working, when i upgrade nativewind to v4

**Expected behavior**
I was querying the view via viewtag on the native side, but after upgrading nativewind, this method is not working.

```ts

const tutkViewRef = useRef(null);

const viewTag = findNodeHandle(tutkViewRef.current);

<XXXView
      ref={tutkViewRef}
/>
```

```kotlin
  val view = appContext.findView<xxx>(viewTag) ?: return null.  // not work
```

**Additional context**
info Fetching system and libraries information...
System:
  OS: macOS 13.6.3
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 34.75 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.5
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/tonyyo/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    Android NDK: 20.0.5594570
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/tonyyo/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by marklawlor** [comment]
This might be fixed in `4.0.31` which fixed a passing ref bug.

I hope this fixes your issue as I'm inclined not to fix issues related to `findNodeHandle` as:
- it was deprecated back in RN 0.69 / 0.70 (technically 0.69 with the release of React 18 but the migration guide came with 0.70)
- unavailable under the new architecture
- can be fixed by simply migrating to `forwardRef` or by [following the guide for classes in the docs](https://reactnative.dev/docs/0.70/new-architecture-library-intro#migrating-findnodehandle--getting-a-hostcomponent)

I'm going to closet this issue for the reasons above, if you think this is unreasonable let me know why in a comment.
