### ISSUE TITLE
v4: shadow-x-{n} and space-y-{n} not working

### ISSUE THREAD

**Issue by mprync** [marklawlor/nativewind#803]
**Describe the bug**
`space-x-{n}` and `space-y-{n}` not working anymore. They were working previously.

This was temporarily removed from v4 as stated https://www.nativewind.dev/v4/tailwind/spacing/space-between

When will this be added back? For this to only be a web feature when it was previously a mobile feature is odd to me.

Can we please get this added back in otherwise this will prevent a lot of projects upgrading to v4...

**Comment by marklawlor** [comment]
`spacing-*` will return, but not for a while. Until then `gap-*` should satisfy 99% of use cases.

It was removed as it:
- Killed performance
- Once worked in one specific use-case and it was hard to understand why it did/didn't work

Because it has these problems, and can large be subsituted via `gap-*`, its not very high to the priority list to get working again. Probably once React Native implements `display: block` I'll re-explore this.

**Comment by becknik** [comment]
Stumbled upon this after wondering why the `space-x` functions are working in web, but not on android.

Is the vscode tailwind plugin able to detect the removal of this function? Mine still lists it as auto completion.
