### ISSUE TITLE
Styles working, except Text Color

### ISSUE THREAD

**Issue by Knaackee** [marklawlor/nativewind#818]
I am in the process of trying native wind (v4) in my expo (router) project.

I was able to set up the project and now trying some styles. All styles work, but text color e.g. `text-red-500` is not working.

```
export default function TabOneScreen() {
  return (
    <Container>
      <Text className="text-3xl font-bold text-green-500">Tab One</Text>
      <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />
      <Container>
        <Text className="text-red-600">Hello</Text>
        <Text className="bg-blue-800 font-bold text-white">World!</Text>
      </Container>
    </Container>
  );
}

const Container = (props: PropsWithChildren) => (
  <View className="flex flex-1 items-center justify-center">{props.children}</View>
);
```

![image](https://github.com/marklawlor/nativewind/assets/880759/5f5f6eea-f3f1-4e74-b5c8-3490c4606f82)

I did a lot of troubleshooting but couldn't find anything. 

Any idea?

**Comment by marklawlor** [comment]
Please provide a full reproduction, there is not enough information here

It looks like your are using custom components. ` <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />`. These are not standard props for the View component.

What happens if you use the `Text`/`View` from React Native?

**Comment by Knaackee** [comment]
Oh man, that's embarrassing. Sorry!

Many thanks for the quick response! Fantastic project.
